# Generated by Django 5.0 on 2023-12-13 18:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_portfolioview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioView',
            new_name='PortfolioViewModel',
        ),
    ]
