# Generated by Django 5.0 on 2023-12-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_portfolioviewmodel_date'),
        ('projects', '0008_projectviewmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
    ]
